### ISSUE TITLE
www.msn.com

### ISSUE THREAD

**Issue by p1r473** [chrisjudk/hosts#9]
**What URL(s)**
a-0003.a-msedge.net

**Affected service**
MSN

**Expected behavior**
www.msn.com is a news site

**Additional context**
This is a CNAME for www.msn.com
That means if you're using deep packet inspection for blocking, MSN will be blocked

**Comment by chrisjudk** [comment]
URL(s):
www.msn.com (cname for www-msn-com.a-0003.a-msedge.net)
www-msn-com.a-0003.a-msedge.net

**Comment by chrisjudk** [comment]
Addressed in d5bea28d512f6cb185b7d6f2072e0fb5f72e76cd

Categorized in 7d4dd7b20148a33e285c4cb38301f42d29a5a47d

pihole script updated in e43a92fd6824acbce7b1f45b4f2fcd54175c4a4b

**Comment by chrisjudk** [comment]
@p1r473 Try loading the whitelist when you get a chance. I believe those two domains are all that needed to be whitelisted to get www.msn.com working.

**Comment by p1r473** [comment]
So I have deep cname inspection enabled, so anything that is a CNAME for msn.com will also block msn.com.

a-0003.a-msedge.net is a CNAME for msn.com so while it's blocked it won't load

I recommend removing a-0003.a-msedge.net too in case other people use your list and also have deep CNAME inspection on in their adblocker.

I've whitelisted a-0003.a-msedge.net locally but still recommend to remove it

**Comment by chrisjudk** [comment]
@p1r473 I'm seeing claims that that specific domain name is used for windows 10 data collection [barracudanetworks](https://community.barracudanetworks.com/forum/index.php?/topic/26627-howto-block-windows-10-data-collection/), [dslreport](https://www.dslreports.com/forum/r31344776-Microsoft-finally-reveals-what-data-Windows-10-really-collects~start=90)
